import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/app.style.css";
import "./styles/editor.style.css";
import "./styles/svg.style.css";
import "./styles/auth.style.css";
import "./styles/org.style.css";
import "./styles/main.style.css";
import { ThemeProvider } from "next-themes";
import SessionClientProvider from "@/components/providers/session-provider";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider attribute="class">
          <Suspense>
            <SessionClientProvider>{children}</SessionClientProvider>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
