name: Fluctux CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "*"
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Database
      MONGO_URI: ${{ secrets.MONGO_URI }}

      # Base URI
      NEXT_PUBLIC_API_BASE_URI: ${{ vars.NEXT_PUBLIC_API_BASE_URI }}

      # NextAuth
      AUTHJS_SECRET: ${{ secrets.AUTHJS_SECRET }}

      # Github
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_RAW_CONTENT_API: ${{ vars.GH_RAW_CONTENT_API }}
      GH_AUTH_DOC_API: ${{ vars.GH_AUTH_DOC_API }}

      # Algolia
      NEXT_PUBLIC_ALGOLIA_APPLICATION_ID: ${{ vars.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID }}
      NEXT_PUBLIC_ALGOLIA_SEARCH_API: ${{ vars.NEXT_PUBLIC_ALGOLIA_SEARCH_API }}
      ALGOLIA_WRITE_API: ${{ secrets.ALGOLIA_WRITE_API }}

      # Arcjet
      ARCJET_KEY: ${{ secrets.ARCJET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug Environment Variables
        run: |
          echo "NEXT_PUBLIC_API_BASE_URI=${NEXT_PUBLIC_API_BASE_URI}"
          echo "AUTHJS_SECRET=${AUTHJS_SECRET}"
          echo "NEXT_PUBLIC_ALGOLIA_APPLICATION_ID=${NEXT_PUBLIC_ALGOLIA_APPLICATION_ID}"
          echo "NEXT_PUBLIC_ALGOLIA_SEARCH_API=${NEXT_PUBLIC_ALGOLIA_SEARCH_API}"
          echo "ALGOLIA_WRITE_API=${ALGOLIA_WRITE_API}"
          echo "ARCJET_KEY=${ARCJET_KEY}"
          echo "MONGO_URI=${MONGO_URI}"
          echo "GH_TOKEN=${GH_TOKEN}"
          echo "GH_RAW_CONTENT_API=${GH_RAW_CONTENT_API}"
          echo "GH_AUTH_DOC_API=${GH_AUTH_DOC_API}"
          echo "NEXT_PUBLIC_ALGOLIA_APPLICATION_ID=${NEXT_PUBLIC_ALGOLIA_APPLICATION_ID}"
          echo "NEXT_PUBLIC_ALGOLIA_SEARCH_API=${NEXT_PUBLIC_ALGOLIA_SEARCH_API}"

      - name: Build Image
        run: |
          docker build -t dockermahin/fluctux:latest \
            --build-arg MONGO_URI=${MONGO_URI} \
            --build-arg NEXT_PUBLIC_API_BASE_URI=${NEXT_PUBLIC_API_BASE_URI} \
            --build-arg AUTHJS_SECRET=${AUTHJS_SECRET} \
            --build-arg NEXT_PUBLIC_ALGOLIA_APPLICATION_ID=${NEXT_PUBLIC_ALGOLIA_APPLICATION_ID} \
            --build-arg NEXT_PUBLIC_ALGOLIA_SEARCH_API=${NEXT_PUBLIC_ALGOLIA_SEARCH_API} \
            --build-arg ALGOLIA_WRITE_API=${ALGOLIA_WRITE_API} \
            --build-arg ARCJET_KEY=${ARCJET_KEY} \
            --build-arg GH_TOKEN=${GH_TOKEN} \
            --build-arg GH_RAW_CONTENT_API=${GH_RAW_CONTENT_API} \
            --build-arg GH_AUTH_DOC_API=${GH_AUTH_DOC_API} .

      - name: Push Image
        run: |
          docker login -u dockermahin -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push dockermahin/fluctux:latest
